# Generated by Django 4.0.3 on 2022-03-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('isPaid', models.BooleanField()),
                ('price', models.IntegerField()),
                ('numSubscribers', models.IntegerField()),
                ('numReveiws', models.IntegerField()),
                ('numPublishedLectures', models.IntegerField()),
                ('instructionalLevel', models.CharField(max_length=200)),
                ('contentInfo', models.CharField(max_length=200)),
                ('publishedTime', models.CharField(max_length=300)),
            ],
        ),
    ]
