# Generated by Django 4.0.3 on 2022-03-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_owner', models.CharField(max_length=200)),
                ('prod_price', models.IntegerField()),
                ('prod_source', models.CharField(max_length=100)),
            ],
        ),
    ]
